---
- name: Install EPEL Repo
  hosts: webservers 
  become: true
  vars:
    nginx_listen_port: 8080
  tasks:
  - name: Install EPEL Repo package from standard repo
    yum:
      name: epel-release
      state: present
  - name: install nginx from repo
    yum:
      name: nginx
      state: latest
    tags:
      - nginx-package
      - packages
  - name: Nginx
    hosts: web
    roles:
      - web_nginx
  - name: Nginx
    hosts: rrobin
    roles:
      - rrobin
